/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author vsbk0
 */
public class ProfessorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorJFrame
     */
    public ProfessorJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        bnaddCourse = new javax.swing.JButton();
        btnviewCourse = new javax.swing.JButton();
        btnaddSchedule = new javax.swing.JButton();
        btnviewSchedule = new javax.swing.JButton();
        btnRubrics = new javax.swing.JButton();
        btnaddGrade = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bnaddCourse.setText("Add Course");
        bnaddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnaddCourseActionPerformed(evt);
            }
        });

        btnviewCourse.setText("View Course");

        btnaddSchedule.setText("Add Schedule");
        btnaddSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddScheduleActionPerformed(evt);
            }
        });

        btnviewSchedule.setText("View Schedule");

        btnRubrics.setText("Rubrics");

        btnaddGrade.setText("Add Grade");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnaddCourse)
                    .addComponent(btnviewCourse)
                    .addComponent(btnaddSchedule)
                    .addComponent(btnviewSchedule)
                    .addComponent(btnRubrics)
                    .addComponent(btnaddGrade))
                .addContainerGap(497, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bnaddCourse, btnRubrics, btnaddGrade, btnaddSchedule, btnviewCourse, btnviewSchedule});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(bnaddCourse)
                .addGap(45, 45, 45)
                .addComponent(btnviewCourse)
                .addGap(54, 54, 54)
                .addComponent(btnaddSchedule)
                .addGap(55, 55, 55)
                .addComponent(btnviewSchedule)
                .addGap(49, 49, 49)
                .addComponent(btnRubrics)
                .addGap(41, 41, 41)
                .addComponent(btnaddGrade)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bnaddCourse, btnRubrics, btnaddGrade, btnaddSchedule, btnviewCourse, btnviewSchedule});

        jSplitPane1.setRightComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnaddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnaddCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnaddCourseActionPerformed

    private void btnaddScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnaddCourse;
    private javax.swing.JButton btnRubrics;
    private javax.swing.JButton btnaddGrade;
    private javax.swing.JButton btnaddSchedule;
    private javax.swing.JButton btnviewCourse;
    private javax.swing.JButton btnviewSchedule;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
