/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author vsbk0
 */
public class ViewCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCourseJPanel
     */
    public ViewCourseJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IbTerm = new javax.swing.JLabel();
        IbcourseNumber = new javax.swing.JLabel();
        txtcourseNumber = new javax.swing.JTextField();
        IbOnline = new javax.swing.JLabel();
        IbcourseName = new javax.swing.JLabel();
        txtcourseName = new javax.swing.JTextField();
        jOnlineButton1 = new javax.swing.JRadioButton();
        Ibdepartment = new javax.swing.JLabel();
        jOffineButton2 = new javax.swing.JRadioButton();
        txtdepartment = new javax.swing.JTextField();
        txtcredits = new javax.swing.JTextField();
        IbCredits = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        IbprofessorName = new javax.swing.JLabel();
        txtprofessorName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        IbTitle = new javax.swing.JLabel();

        IbTerm.setText("Term :");

        IbcourseNumber.setText("Course Number :");

        IbOnline.setText("Online/Offline :");

        IbcourseName.setText("Course Name :");

        jOnlineButton1.setText("Online");
        jOnlineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOnlineButton1ActionPerformed(evt);
            }
        });

        Ibdepartment.setText("Department :");

        jOffineButton2.setText("Offline");

        IbCredits.setText("Credits :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Spring 2023", "Fall 2023", "Spring 2024", " " }));

        IbprofessorName.setText("Professor Name :");

        btnUpdate.setText("Update Course");

        IbTitle.setText("View Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(IbTitle)))
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ibdepartment)
                        .addComponent(IbcourseName)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IbprofessorName)
                            .addComponent(IbcourseNumber))
                        .addComponent(IbOnline)
                        .addComponent(IbCredits)
                        .addComponent(IbTerm))
                    .addGap(135, 135, 135)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtprofessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jOnlineButton1)
                                    .addComponent(txtcredits)
                                    .addComponent(jComboBox1, 0, 118, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jOffineButton2)))
                    .addContainerGap(103, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtcourseName, txtcourseNumber, txtdepartment, txtprofessorName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(IbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IbprofessorName)
                        .addComponent(txtprofessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IbcourseNumber)
                        .addComponent(txtcourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IbcourseName)
                        .addComponent(txtcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ibdepartment)
                        .addComponent(txtdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IbOnline)
                        .addComponent(jOnlineButton1)
                        .addComponent(jOffineButton2))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IbCredits)
                        .addComponent(txtcredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IbTerm)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(93, 93, 93)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtcourseName, txtcourseNumber, txtdepartment, txtprofessorName});

    }// </editor-fold>//GEN-END:initComponents

    private void jOnlineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOnlineButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOnlineButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbCredits;
    private javax.swing.JLabel IbOnline;
    private javax.swing.JLabel IbTerm;
    private javax.swing.JLabel IbTitle;
    private javax.swing.JLabel IbcourseName;
    private javax.swing.JLabel IbcourseNumber;
    private javax.swing.JLabel Ibdepartment;
    private javax.swing.JLabel IbprofessorName;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JRadioButton jOffineButton2;
    private javax.swing.JRadioButton jOnlineButton1;
    private javax.swing.JTextField txtcourseName;
    private javax.swing.JTextField txtcourseNumber;
    private javax.swing.JTextField txtcredits;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtprofessorName;
    // End of variables declaration//GEN-END:variables
}
